AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Application template 
  
Globals:
  Function:
    Timeout: 3

Resources:
  GreetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  TeamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: new.handler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /players
            Method: get

#  POSTFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: hello-world/
#      Handler: post.handler
#      Runtime: nodejs10.x
#      Events:
#        HelloWorld:
#          Type: Api
#          Properties:
#            Path: /postreq
#            Method: post
#  GetS3Function:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: hello-world/
#      Handler: getS3.handler
#      Runtime: nodejs10.x
#      Policies: 
#        - AmazonS3FullAccess
#      Events:
#        HelloWorld:
#          Type: Api
#          Properties:
#            Path: /gets3
#            Method: post

  returnS3Buckets:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bucketlist.handler
      Runtime: nodejs8.10
      CodeUri: ./
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListAllMyBuckets"
            Resource: '*'
      DeploymentPreference:
          Type: Linear10PercentEvery1Minute
          Hooks:
            PreTraffic: !Ref preTrafficHook
      Events:
        Api:
          Type: Api
          Properties:
            Path: /test
            Method: get



  preTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: preTrafficHook.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource: !Ref returnS3Buckets.Version
      Runtime: nodejs8.10
      FunctionName: 'CodeDeployHook_preTrafficHook_sam'
      DeploymentPreference:
        Enabled: false
      Timeout: 8
      Environment:
        Variables:
          NewVersion: !Ref returnS3Buckets.Version
